### ISSUE TITLE
Need to store temp export files in folders including `export_id` to avoid collisions

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter-exporter-sinatra#21]
assuming potentially more than one export would be run in the same container, we should modify `mapknitter-exporter` to include `export_id`, OR we could concatenate the `export_id` to this line: 

https://github.com/publiclab/mapknitter-exporter-sinatra/blob/f51be244945116c412b5d3bf8b82832fe244e7c0/app.rb#L69

**Comment by jywarren** [comment]
https://github.com/publiclab/mapknitter-exporter-sinatra/pull/22

**Comment by icarito** [comment]
Fixed in #22 - Thanks!
