### ISSUE TITLE
Produce and update `status.json` as Google Cloud storage object

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter-exporter-sinatra#4]
However, we should try to abstract, or at least document well, the code we use to save/update this file, in case future users want to do this on AWS or another file storage solution.

**Comment by jywarren** [comment]
Noting that to continue the export process, we may need to use background processes, so we can offer the `status.json` immediately while the job continues...

This could help? https://stackoverflow.com/a/9911695

```ruby
  @@pid = Process.spawn('external_command_to_run')
```

but we really want to be able to run a whole Sinatra function asynchronously... not sure about that part

**Comment by jywarren** [comment]
ok we are now seeing `upstream request timeout` - this may relate to the background job issue. Exports run a long time.

**Comment by jywarren** [comment]
Would we need https://github.com/mperham/sidekiq?

**Comment by jywarren** [comment]
(from publiclab/mapknitter#364) we can soon try this one with a lot of images: https://mapknitter.org/maps/irish-uk-border-mapping/warpables.json

**Comment by jywarren** [comment]
https://export.mapknitter.org/export?url=https://mapknitter.org/maps/ceres--2/warpables.json

Bigger set: https://export.mapknitter.org/export?url=https://mapknitter.org/maps/irish-uk-border-mapping/warpables.json

**Comment by jywarren** [comment]
And noting we may need to increase the RAM to over the current 1gb

**Comment by jywarren** [comment]
https://github.com/tkak/sinatra-sidekiq-example/blob/master/lib/some_worker.rb

https://github.com/tkak/sinatra-sidekiq-example/blob/e2fc086d7f67b525774c5e5a9602c6fcedb60054/app.rb#L18-L26

Aha!

**Comment by jywarren** [comment]
I added parameters for scale and this can run faster and get farther without timing out: https://export.mapknitter.org/export?url=https://mapknitter.org/maps/ceres--2/warpables.json&scale=30

**Comment by jywarren** [comment]
:tada: 

![Screenshot_20190414-191302](https://user-images.githubusercontent.com/24359/56101447-65cf8300-5ee9-11e9-93a9-4ceebb5774a8.png)

**Comment by icarito** [comment]
> However, we should try to abstract, or at least document well, the code we use to save/update this file, in case future users want to do this on AWS or another file storage solution.

This was achieved by using Fog http://fog.io/storage/

:-)
