### ISSUE TITLE
https access (for JavaScript)

### ISSUE THREAD

**Issue by jywarren** [publiclab/mapknitter-exporter-sinatra#40]
https://cloud.google.com/load-balancing/docs/ssl-certificates

https://stackoverflow.com/questions/3696558/how-to-make-sinatra-work-over-https-ssl#5099597

**Comment by jywarren** [comment]
https://console.cloud.google.com/appengine/settings/certificates?project=public-lab&authuser=1

**Comment by jywarren** [comment]
Ok, we've been configuring DNS around this...

**Comment by icarito** [comment]
DONE!
